"""adding products and inventories

Revision ID: c258c95d4212
Revises: 7d9ba7c31d20
Create Date: 2026-01-15 03:18:42.809690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c258c95d4212'
down_revision: Union[str, Sequence[str], None] = '7d9ba7c31d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'name', name='uq_product_pharmacy_name')
    )
    op.create_index(op.f('ix_products_pharmacy_id'), 'products', ['pharmacy_id'], unique=False)
    op.create_table('inventories',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventories_product_id'), 'inventories', ['product_id'], unique=True)
    op.drop_index(op.f('ix_pharmacy_invites_email'), table_name='pharmacy_invites')
    op.drop_index(op.f('ix_pharmacy_invites_pharmacy_id'), table_name='pharmacy_invites')
    op.drop_index(op.f('ix_pharmacy_invites_role'), table_name='pharmacy_invites')
    op.drop_index(op.f('ix_pharmacy_invites_token'), table_name='pharmacy_invites')
    op.drop_table('pharmacy_invites')
    op.drop_index(op.f('ix_email_otps_user_id'), table_name='email_otps')
    op.drop_table('email_otps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_otps',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('otp_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('email_otps_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_otps_pkey'))
    )
    op.create_index(op.f('ix_email_otps_user_id'), 'email_otps', ['user_id'], unique=False)
    op.create_table('pharmacy_invites',
    sa.Column('pharmacy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('pharmacy_invites_pharmacy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pharmacy_invites_pkey'))
    )
    op.create_index(op.f('ix_pharmacy_invites_token'), 'pharmacy_invites', ['token'], unique=True)
    op.create_index(op.f('ix_pharmacy_invites_role'), 'pharmacy_invites', ['role'], unique=True)
    op.create_index(op.f('ix_pharmacy_invites_pharmacy_id'), 'pharmacy_invites', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_invites_email'), 'pharmacy_invites', ['email'], unique=False)
    op.drop_index(op.f('ix_inventories_product_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_products_pharmacy_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
