"""add pharmacy invites

Revision ID: c6afc9cacd36
Revises: 103e21223b2b
Create Date: 2026-01-16 21:51:35.724657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6afc9cacd36'
down_revision: Union[str, Sequence[str], None] = '103e21223b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_invites',
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_invites_email'), 'pharmacy_invites', ['email'], unique=False)
    op.create_index(op.f('ix_pharmacy_invites_pharmacy_id'), 'pharmacy_invites', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_invites_role'), 'pharmacy_invites', ['role'], unique=True)
    op.create_index(op.f('ix_pharmacy_invites_token'), 'pharmacy_invites', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_invites_token'), table_name='pharmacy_invites')
    op.drop_index(op.f('ix_pharmacy_invites_role'), table_name='pharmacy_invites')
    op.drop_index(op.f('ix_pharmacy_invites_pharmacy_id'), table_name='pharmacy_invites')
    op.drop_index(op.f('ix_pharmacy_invites_email'), table_name='pharmacy_invites')
    op.drop_table('pharmacy_invites')
    # ### end Alembic commands ###
