class ErrorMessages:
    ERR_COULD_NOT_VALIDATE = "Could not validate credentials"
    ERR_OTP_INVALID = "Invalid or expired OTP"
    ERR_INVALID_CRED = "Invalid Credentials"
    ERR_USER_EXISTS = "User already exists"
    EER_PHARM_NOT_FOUND = "Pharmacy not found"
    ERR_PHARMACY_ACCESS_DENIED = "Access Denied"
    ERR_INSUFFICIENT_PERMISSIONS = "Insufficient permissions"
    ERR_INVALID_ROLE = "Invalid Role"
    ERR_INVITE_NOT_FOUND = "Invite not found"
    ERR_INVITE_ALREADY_USED = "Invite Used"
    ERR_INVITE_EXPIRED = "Invite Expired"
    ERR_INVITE_EMAIL_MISMATCH = "Entry Mismatch"
    ERR_PERMISSION_DENIED = "Denied"
    ERR_PRODUCT_ALREADY_EXISTS = "Product Already Exists"